### PR TITLE
fix input handling

### LINKED ISSUE #243: Setting mediaType doesn't work
What version of octokit is used in this action? I'm trying to get the contents of a file in a repository with:
```
github.rest.repos.getContent({
  owner,
  repo,
  path,
  mediaType: {
    format: "raw+json"
  }
});
```
but it doesn't work. I always get the default response as if mediaType isn't set. Maybe this is not yet supported in the octokit client used in this action?

I looked at the debug information of the request and the headers don't include an `Accept` header. I expect the `Accept` header to be set to `application/vnd.github.v3.raw+json`

### PR DESCRIPTION
**Pull request by mjpieters**
This PR fixes how github-script handles the inputs given, which in turn
unbreaks how the Octokit request defaults are set.

I've included an extra ESLint rule to guard against the error in future, as
well as expanded the integration tests to cover action settings better.

- Clean and spruce up the integration tests a bit
  - Use test-specific step ids
  - Remove unused input parameters
  - Provide clear output on what passed or failed, including a step summary for each passed test.
- Fix null handling, covered by integration tests
  - `core.getInput()` always returns a string, so testing for 'not null' is always true. This then leads to previews set to an array with a single empty string, breaking accept-header output.
  - Updated eslint rules should help avoid this issue in future, and new integration tests verify that the github client configuration now reflects the intended configuration options.

Fixes #243

### CODE REVIEW

**Comment by mjpieters** [comment]
See https://github.com/mjpieters/github-script/actions/runs/4566102017 for an example of what the integration test summaries look like.

File: src/main.ts [hunk 1]
```diff
@@ -38,11 +38,12 @@ async function main(): Promise<void> {
...
-  if (userAgent != null) opts.userAgent = userAgent
-  if (previews != null) opts.previews = previews.split(',')
-  if (retryOpts) opts.retry = retryOpts
+  const opts: Options = {
+    retry: retryOpts
+  }
+  if (debug) opts.log = console
+  if (userAgent) opts.userAgent = userAgent
+  if (previews) opts.previews = previews.split(',')
   if (requestOpts) opts.request = requestOpts
```
Comment (joshmgross) [inline src/main.ts:47]: Would this be equivalent?

```ts
  const opts: Options = {
    log: debug ? console : undefined,
    userAgent: userAgent || undefined,
    previews: previews ? previews.split(',') : undefined,
    retry: retryOpts,
    request: requestOpts
  }
```

**Review by joshmgross — APPROVED** [review]
Left one suggestion, but not a blocker. Thanks for adding all those integration tests!

File: src/main.ts (hunk 1 above)
Comment (mjpieters) [reply src/main.ts:47]: It would be. I'll make the change.

**Review by joshmgross — APPROVED** [review]
